### ISSUE TITLE
Chunk-level checksums

### ISSUE THREAD

**Issue by charlesdaniels** [charlesdaniels/bitshuffle#4]
Currently, each packet carries the checksum for the entire file with it. Instead, it should carry the checksum for the chunk it contains. A new, optional field should be added to the packet format which will contain the checksum for the whole file, so it is only transmitted once or twice. This will also be useful, because we can tell the user exactly which packet has been damaged.

I would suggest designing this feature such that all "whole file" checksums get accumulated in a list. If any of them do not match the others, then BitShuffle assumes that the entire stream is corrupt and should throw a warning (although the file should still be written, as the user may be using a parity tool like `par2` independently).

**Comment by jyn514** [comment]
I was thinking of only storing the first checksum and matching all others against it. If any did not match, only one warning would be thrown.

**Comment by charlesdaniels** [comment]
So only the first chunk would contain the checksum for the whole file?

Maybe if we made the checksum field  optional, then assert that all checksums should be equal, and that the whole file should match them. Then we only put the checksum in the first and last packet. 

The only argument for the block level checksums would be that you would know *which* block was corrupt. 

- - - - 

This email was sent from my smartphone.

**Comment by jyn514** [comment]
Sorry, I didn't explain clearly. I was assuming each chunk would carry both a chunk-level hash and a file hash. My suggestion was to, as an implementation detail, only store the first file hash, since we don't store the hashes after they're checked in any case. We would then check the first hash against later hashes, and discard the later hashes after checking.

Additionally, we would check the hash for each packet and print to stderr which packets were incorrect, or if none were. If none are incorrect, but the file hash is, that would imply that only the file-level hash had been corrupted and the contents is still intact.

**Comment by charlesdaniels** [comment]
If I understand what you are suggesting, I believe that would work just fine.

**Comment by jyn514** [comment]
Draft release in https://github.com/charlesdaniels/bitshuffle/commit/d6cf080467e1a6ffb9b1bfc06aa0bff1c85022f6.

**Comment by jyn514** [comment]
Addressed in https://github.com/charlesdaniels/bitshuffle/pull/46. Would like @charlesdaniels to give a sanity check, but clear to merge otherwise.

**Comment by jyn514** [comment]
Done in https://github.com/charlesdaniels/bitshuffle/pull/46
